Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name, email and UFID.
Please do not modify instruction cells or any cells with automated tests (marked with `[ASSERTS]`). Note: you can add new cells if you need them, but answers must be in the cells with `YOUR CODE HERE` or "YOUR ANSWER HERE" comments.

---

# Homework 0: Setting Up Your Environment!

## Preamble: Write your Name, Email and UFID

In [1]:
NAME = 'Tre\' Jeter'
EMAIL = 't.jeter@ufl.edu'
UFID = 19469876

# YOUR CODE HERE

In [2]:
""" [ASSERTS] Check that your name, email, and UFID is filled in."""
assert NAME != '' and NAME != 'Your name here.' and len(NAME) > 3
assert EMAIL != '' and EMAIL != 'Your email here.' and len(EMAIL) > 7
assert type(UFID) == int and UFID != 12345678 and UFID >= 10000000 and UFID <= 99999999

## Academic Integrity

### <span style="color:red;">This is an individual assignment. Academic integrity violations (i.e., cheating, plagiarism) will be reported to SCCR!</span><br/>
#### The official CISE policy recommended for such offenses is a course grade of E. Additional sanctions may be imposed by SCCR such as marks on your permanent educational transcripts, dismissal or expulsion.
#### Reminder of the Honor Pledge: On all work submitted for credit by Students at the University of Florida, the following pledge is either required or implied: *"On my honor, I have neither given nor received unauthorized aid in doing this assignment."*

#### Acknowledgement: Do you acknowledge and understand the academic integrity warning above? 

In [3]:
academic_integrity_acknowledgement = True #False
# YOUR CODE HERE

In [4]:
""" [ASSERTS] Check that you acknowledge the academic integrity warning, you understanding it and have been reminded of the UF Honor Pledge."""
assert academic_integrity_acknowledgement

---
# [Task 1] Check that the cell below runs with no errors and that the version of Python is at least 3.8 and the version of Tensorflow is at least 2.1!

In [5]:
# Load packages we need
import sys
import os

import numpy as np
import scipy as sp
import pandas as pd

import sklearn

import matplotlib 

import tensorflow as tf

# Let's check our software versions
print('### Python version: ' + sys.version)
print('### Numpy version: ' + np.__version__)
print('### Scipy version: ' + sp.__version__)
print('### Pandas version: ' + pd.__version__)
print('### Scikit-learn version: ' + sklearn.__version__)
print('### Matplotlib version: ' + matplotlib.__version__)
print('### TensorFlow version: ' + tf.__version__)
print('------------')

### Python version: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
### Numpy version: 1.20.3
### Scipy version: 1.7.1
### Pandas version: 1.5.2
### Scikit-learn version: 1.0.2
### Matplotlib version: 3.4.3
### TensorFlow version: 2.8.0
------------


### [Task 1] (15 Points) Paste in the cell below the output of the cell above (with the library versions)!

<!-- Paste the output here: -->
\#\#\# Python version: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]

\#\#\# Numpy version: 1.20.3

\#\#\# Scipy version: 1.7.1

\#\#\# Pandas version: 1.5.2

\#\#\# Scikit-learn version: 1.0.2

\#\#\# Matplotlib version: 3.4.3

\#\#\# TensorFlow version: 2.8.0

\------------
<!-- # YOUR CODE HERE -->

In [6]:
""" [ASSERTS] Check environment and versions."""
python_ver_split = sys.version.split('.')
assert int(python_ver_split[0]) >= 3 and int(python_ver_split[1]) >= 8
tf_ver_split = tf.__version__.split('.')
assert int(tf_ver_split[0]) >= 2 and int(tf_ver_split[1]) >= 1

---
# [Task 2] (10 Points) Tell us a little bit about yourself and what you hope to learn in this course

## [Task 2a] (5 Points) Write a brief description of your academic history (2-3 sentences is fine)

<!-- YOUR CODE HERE -->
I received my Bachelors of Science in Computer Science and Computer Engineering from Claflin University in 2021. I am currently a 3rd-year Ph.D. student researching at the intersection of security and privacy as it pertains to Federated Learning.

## [Task 2b] (5 Points) Briefly describe what you hope to learn in this course (a few sentences is fine)

<!-- YOUR CODE HERE -->
I hope to understand the foundational principles of machine learning better. Although I'm researching federated learning, I do not have a formal ML background and this course could help with that.

---
# [Task 3] (25 Points) Familiarize yourself with Python and NumPy and write some code to demonstrate your understanding. (Note: the basics notebook is a great resource!)

## [Task 3a] (5 Points) Create a numpy array 'a' that contains the integers 0 to 10. The shape of it should be (11,).

In [7]:
"""Put your code to create 'a' here.
"""
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
# YOUR CODE HERE

In [8]:
""" [ASSERTS] Check the answer."""
print(a) # this should print: "[ 0 1  2  3  4  5  6  7  8  9 10]"
assert a.shape == (11,)

[ 0  1  2  3  4  5  6  7  8  9 10]


## [Task 3b] (5 Points) Let 'b' be the numpy array where every element is the square of the corresponding element in 'a'. The shape should be (11,).

In [9]:
"""Put your code to create 'b' here.
"""
b = np.square(a)
# YOUR CODE HERE

In [10]:
""" [ASSERTS] Check the answer."""
print(b) # this should print: "[  0   1   4   9  16  25  36  49  64  81 100]"
assert b.shape == (11,)

[  0   1   4   9  16  25  36  49  64  81 100]


## [Task 3c] (5 Points) Create an 3x4 numpy array 'c' of random integers in [-5, +5[ (use numpy.random.randint).

In [11]:
"""Put your code to create 'c' here.
"""
# seed the random number generated
np.random.seed(42) 

c = np.random.randint(-5, 5, size=(3, 4))
# YOUR CODE HERE

In [12]:
""" [ASSERTS] Check the answer."""
print(c)
assert c.shape == (3,4)

[[ 1 -2  2 -1]
 [ 1  4 -3  1]
 [ 2 -1 -2  2]]


## [Task 3d] (5 Points) Let 'd' be the reshaped version of 'c' as a 6x2 array.

In [13]:
"""Put your code to create 'd' here.
"""
d = c.reshape(6,2)
# YOUR CODE HERE

In [14]:
""" [ASSERTS] Check the answer."""
print(d)
assert d.shape == (6,2)

[[ 1 -2]
 [ 2 -1]
 [ 1  4]
 [-3  1]
 [ 2 -1]
 [-2  2]]


## [Task 3e] (5 Points) Use numpy or scipy to draw 1000 i.i.d. random samples from the Gaussian distribution with the mean given by the first digit of your UFID and the standard deviation given by the square root of the sum of all digits in your UFID. For example, if you UFID is 2801104 the mean would be 2 and the standard deviation is 4. Let 'e' be the array with the random samples.

In [15]:
"""Put your code to create 'e' here.
"""
import scipy
import scipy.stats as stats

e = stats.norm.rvs(size=1000, loc=1, scale=7) # scale ~7.07
# YOUR CODE HERE

In [16]:
""" [ASSERTS] Check the answer."""
assert e.shape == (1000,) or e.shape == (1000,1)